/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as BoardsSlugRouteImport } from './routes/boards.$slug'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as WatchSlugLectureIdRouteImport } from './routes/watch.$slug.$lectureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsSlugRoute = BoardsSlugRouteImport.update({
  id: '/boards/$slug',
  path: '/boards/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugLectureIdRoute = WatchSlugLectureIdRouteImport.update({
  id: '/watch/$slug/$lectureId',
  path: '/watch/$slug/$lectureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/readiness': typeof ReadinessRoute
  '/boards/$slug': typeof BoardsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/watch/$slug/$lectureId': typeof WatchSlugLectureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/readiness': typeof ReadinessRoute
  '/boards/$slug': typeof BoardsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/watch/$slug/$lectureId': typeof WatchSlugLectureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/readiness': typeof ReadinessRoute
  '/boards/$slug': typeof BoardsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/watch/$slug/$lectureId': typeof WatchSlugLectureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/readiness'
    | '/boards/$slug'
    | '/programs/$slug'
    | '/watch/$slug/$lectureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/readiness'
    | '/boards/$slug'
    | '/programs/$slug'
    | '/watch/$slug/$lectureId'
  id:
    | '__root__'
    | '/'
    | '/readiness'
    | '/boards/$slug'
    | '/programs/$slug'
    | '/watch/$slug/$lectureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadinessRoute: typeof ReadinessRoute
  BoardsSlugRoute: typeof BoardsSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  WatchSlugLectureIdRoute: typeof WatchSlugLectureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$slug': {
      id: '/boards/$slug'
      path: '/boards/$slug'
      fullPath: '/boards/$slug'
      preLoaderRoute: typeof BoardsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug/$lectureId': {
      id: '/watch/$slug/$lectureId'
      path: '/watch/$slug/$lectureId'
      fullPath: '/watch/$slug/$lectureId'
      preLoaderRoute: typeof WatchSlugLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadinessRoute: ReadinessRoute,
  BoardsSlugRoute: BoardsSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  WatchSlugLectureIdRoute: WatchSlugLectureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
